/// High-fidelity representation of the actual security and verification telemetry
/// generated by the Python QDS research core (via the QDS Gateway).
///
/// Preserves raw backend values without inventing threat scores or severities.
class SecurityTelemetry {
  const SecurityTelemetry({
    this.finalDecision,
    this.likelyAttackType,
    this.classicalSignatureValid,
    this.qdsValid,
    this.replayDetected,
    this.verificationAccuracy,
    this.errorRate,
    this.quantumBitCount,
    this.totalShots,
    this.correctShots,
    this.threshold,
    this.qdsDecision,
    this.signerId,
    this.rawTelemetry = const {},
  });

  /// The final decision string from the research pipeline (e.g. "TRUSTED", "INVALID / SUSPICIOUS").
  final String? finalDecision;

  /// The classified attack type from the research core (e.g. "LEGITIMATE", "REPLAY", "CHANNEL_ATTACK", "FORGERY_OR_IMPERSONATION", "NONE").
  final String? likelyAttackType;

  /// Whether the classical Ed25519 digital signature verified successfully.
  final bool? classicalSignatureValid;

  /// Whether the quantum-inspired digital signature verified successfully.
  final bool? qdsValid;

  /// Whether a nonce/signature ID replay was detected.
  final bool? replayDetected;

  /// Measured quantum verification accuracy (0.0 to 1.0).
  final double? verificationAccuracy;

  /// Measured quantum error rate (0.0 to 1.0).
  final double? errorRate;

  /// Number of qubits used in the signature verification circuit.
  final int? quantumBitCount;

  /// Total number of measurement shots executed.
  final int? totalShots;

  /// Number of measurement shots matching the expected quantum state.
  final int? correctShots;

  /// Accuracy threshold required for QDS validation.
  final double? threshold;

  /// Decision code from the QDS module (e.g. "VALID", "INVALID", "ACCEPT", "NOT VERIFIED").
  final String? qdsDecision;

  /// Identity of the key that signed the message (e.g. "X", "Alice").
  final String? signerId;

  /// Raw untouched telemetry map from the backend.
  final Map<String, dynamic> rawTelemetry;

  /// Whether any real telemetry was parsed.
  bool get isEmpty =>
      rawTelemetry.isEmpty &&
      finalDecision == null &&
      likelyAttackType == null &&
      classicalSignatureValid == null &&
      qdsValid == null;

  bool get isNotEmpty => !isEmpty;

  String get displayVerificationAccuracy =>
      verificationAccuracy != null ? '${(verificationAccuracy! * 100).toStringAsFixed(1)}%' : 'Unavailable';

  String get displayErrorRate =>
      errorRate != null ? '${(errorRate! * 100).toStringAsFixed(1)}%' : 'Unavailable';

  String get displayShots =>
      (correctShots != null && totalShots != null) ? '$correctShots / $totalShots' : 'Unavailable';

  String get displayClassicalSignature =>
      classicalSignatureValid == null ? 'Unavailable' : (classicalSignatureValid! ? 'Valid' : 'Invalid');

  String get displayQdsVerification =>
      qdsValid == null ? 'Unavailable' : (qdsValid! ? 'Valid' : 'Invalid');

  String get displayReplayDetection =>
      replayDetected == null ? 'Unavailable' : (replayDetected! ? 'Replay detected' : 'Not detected');

  String get displayThreshold =>
      threshold != null ? threshold!.toStringAsFixed(2) : 'Unavailable';

  String get displaySigner => signerId ?? 'Unknown';

  String get displayAttackType {
    if (likelyAttackType == null) return 'None';
    switch (likelyAttackType!.toUpperCase()) {
      case 'NONE':
      case 'LEGITIMATE':
        return 'Legitimate (None)';
      case 'REPLAY':
        return 'Replay Attack';
      case 'CHANNEL_ATTACK':
        return 'Channel Manipulation';
      case 'FORGERY_OR_IMPERSONATION':
      case 'FORGERY':
        return 'Signature Forgery';
      case 'IMPERSONATION':
        return 'Impersonation Attack';
      default:
        return likelyAttackType!;
    }
  }

  String get displayFinalDecision => finalDecision ?? 'Unavailable';

  /// Safe factory parser for backend `security` maps.
  factory SecurityTelemetry.fromJson(Map<String, dynamic>? json) {
    if (json == null || json.isEmpty) {
      return const SecurityTelemetry();
    }

    double? parseDouble(dynamic value) {
      if (value == null) return null;
      if (value is num) return value.toDouble();
      if (value is String) return double.tryParse(value);
      return null;
    }

    int? parseInt(dynamic value) {
      if (value == null) return null;
      if (value is num) return value.toInt();
      if (value is String) return int.tryParse(value);
      return null;
    }

    bool? parseBool(dynamic value) {
      if (value == null) return null;
      if (value is bool) return value;
      if (value is String) {
        if (value.toLowerCase() == 'true') return true;
        if (value.toLowerCase() == 'false') return false;
      }
      return null;
    }

    return SecurityTelemetry(
      finalDecision: json['final_decision'] as String?,
      likelyAttackType: json['likely_attack_type'] as String?,
      classicalSignatureValid: parseBool(json['classical_signature_valid']),
      qdsValid: parseBool(json['qds_valid']),
      replayDetected: parseBool(json['replay_detected']),
      verificationAccuracy: parseDouble(json['verification_accuracy']),
      errorRate: parseDouble(json['error_rate']),
      quantumBitCount: parseInt(json['quantum_bit_count']),
      totalShots: parseInt(json['total_shots']),
      correctShots: parseInt(json['correct_shots']),
      threshold: parseDouble(json['threshold']),
      qdsDecision: json['qds_decision'] as String?,
      signerId: json['signer_id'] as String?,
      rawTelemetry: Map<String, dynamic>.from(json),
    );
  }

  Map<String, dynamic> toJson() => {
        if (finalDecision != null) 'final_decision': finalDecision,
        if (likelyAttackType != null) 'likely_attack_type': likelyAttackType,
        if (classicalSignatureValid != null) 'classical_signature_valid': classicalSignatureValid,
        if (qdsValid != null) 'qds_valid': qdsValid,
        if (replayDetected != null) 'replay_detected': replayDetected,
        if (verificationAccuracy != null) 'verification_accuracy': verificationAccuracy,
        if (errorRate != null) 'error_rate': errorRate,
        if (quantumBitCount != null) 'quantum_bit_count': quantumBitCount,
        if (totalShots != null) 'total_shots': totalShots,
        if (correctShots != null) 'correct_shots': correctShots,
        if (threshold != null) 'threshold': threshold,
        if (qdsDecision != null) 'qds_decision': qdsDecision,
        if (signerId != null) 'signer_id': signerId,
      };

  SecurityTelemetry copyWith({
    String? finalDecision,
    String? likelyAttackType,
    bool? classicalSignatureValid,
    bool? qdsValid,
    bool? replayDetected,
    double? verificationAccuracy,
    double? errorRate,
    int? quantumBitCount,
    int? totalShots,
    int? correctShots,
    double? threshold,
    String? qdsDecision,
    String? signerId,
    Map<String, dynamic>? rawTelemetry,
  }) {
    return SecurityTelemetry(
      finalDecision: finalDecision ?? this.finalDecision,
      likelyAttackType: likelyAttackType ?? this.likelyAttackType,
      classicalSignatureValid: classicalSignatureValid ?? this.classicalSignatureValid,
      qdsValid: qdsValid ?? this.qdsValid,
      replayDetected: replayDetected ?? this.replayDetected,
      verificationAccuracy: verificationAccuracy ?? this.verificationAccuracy,
      errorRate: errorRate ?? this.errorRate,
      quantumBitCount: quantumBitCount ?? this.quantumBitCount,
      totalShots: totalShots ?? this.totalShots,
      correctShots: correctShots ?? this.correctShots,
      threshold: threshold ?? this.threshold,
      qdsDecision: qdsDecision ?? this.qdsDecision,
      signerId: signerId ?? this.signerId,
      rawTelemetry: rawTelemetry ?? this.rawTelemetry,
    );
  }
}
